apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}-web
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
{{- if .Values.service.web.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.web.loadBalancerIP }}
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}-backend
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: 22000
      targetPort: sync-listen
      protocol: TCP
      name: sync-listen
    - port: 21027
      targetPort: discovery
      protocol: UDP
      name: discovery
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
{{- if .Values.service.backend.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.backend.loadBalancerIP }}
{{- end }}
